In [15]:
import pandas as pd

In [16]:
pokemon_df = pd.read_csv('pokemon.csv')

In [17]:
pokemon_df.rename(columns={'national_number':'Nº'},inplace=True)

In [18]:
pokemon_df.head(10)

,Nº,gen,Name,primary_type,secondary_type,percent_male,percent_female,height_m,weight_kg,capture_rate,...,against_dragon,against_dark,against_steel,against_fairy,is_sublegendary,is_legendary,is_mythical,gigantamax,mega_evolution,mega_evolution_alt
0,1,I,Bulbasaur,grass,poison,88.14,11.86,0.7,6.9,45,...,1.0,1.0,1.0,0.5,0,0,0,NaN,NaN,NaN
1,2,I,Ivysaur,grass,poison,88.14,11.86,1.0,13.0,45,...,1.0,1.0,1.0,0.5,0,0,0,NaN,NaN,NaN
2,3,I,Venusaur,grass,poison,88.14,11.86,2.0,100.0,45,...,1.0,1.0,1.0,0.5,0,0,0,Gigantamax Venusaur,Mega Venusaur,NaN
3,4,I,Charmander,fire,NaN,88.14,11.86,0.6,8.5,45,...,1.0,1.0,0.5,0.5,0,0,0,NaN,NaN,NaN
4,5,I,Charmeleon,fire,NaN,88.14,11.86,1.1,19.0,45,...,1.0,1.0,0.5,0.5,0,0,0,NaN,NaN,NaN
5,6,I,Charizard,fire,flying,88.14,11.86,1.7,90.5,45,...,1.0,1.0,0.5,0.5,0,0,0,Gigantamax Charizard,Mega Charizard X,Mega Charizard Y
6,7,I,Squirtle,water,NaN,88.14,11.86,0.5,9.0,45,...,1.0,1.0,0.5,1.0,0,0,0,NaN,NaN,NaN
7,8,I,Wartortle,water,NaN,88.14,11.86,1.0,22.5,45,...,1.0,1.0,0.5,1.0,0,0,0,NaN,NaN,NaN
8,9,I,Blastoise,water,NaN,88.14,11.86,1.6,85.5,45,...,1.0,1.0,0.5,1.0,0,0,0,Gigantamax Blastoise,Mega Blastoise,NaN
9,10,I,Caterpie,bug,NaN,50.2,49.8,0.3,2.9,255,...,1.0,1.0,1.0,1.0,0,0,0,NaN,NaN,NaN

# Ranking dos melhores Pokémon de cada tipo por Atríbuto

Informe o tipo do Pokemon

In [19]:
tipo = input('Informe o tipo do pokemon (em ingês): ')

Informe o tipo do pokemon (em ingês): dragon

In [20]:
selecao_tipo = (pokemon_df['primary_type'] == tipo) & (pokemon_df['gen'] != 'VIII') & (pokemon_df['gen'] != 'VII') & (pokemon_df['gen'] != 'VI')
pokemon_tipo = pokemon_df[selecao_tipo]

In [21]:
quantidade_pokemon=pokemon_tipo.shape[0]
print(f'Pokémon tipo: {tipo}')
print(f'Quantidade de Pokémon do tipo escolhido: {quantidade_pokemon}')

Pokémon tipo: dragon
Quantidade de Pokémon do tipo escolhido: 20

In [22]:
ranking_tipo = pokemon_tipo[['Nº','gen','Name','primary_type','height_m','weight_kg','hp','attack','defense','sp_attack','sp_defense','speed']]

# Top 10 Pokémon - Melhor HP

In [23]:
ranking_tipo.sort_values('hp',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,646,V,Kyurem,dragon,3.0,325.0,125,130,90,130,90,95
1,445,IV,Garchomp,dragon,1.9,95.0,108,130,95,80,85,102
2,384,III,Rayquaza,dragon,7.0,206.5,105,150,90,150,90,95
3,644,V,Zekrom,dragon,2.9,345.0,100,150,120,120,100,90
4,643,V,Reshiram,dragon,3.2,330.0,100,120,100,150,120,90
5,373,III,Salamence,dragon,1.5,102.6,95,135,80,110,80,100
6,149,I,Dragonite,dragon,2.2,210.0,91,134,95,100,100,80
7,380,III,Latias,dragon,1.4,40.0,80,80,90,110,130,110
8,381,III,Latios,dragon,2.0,60.0,80,90,80,130,110,110
9,621,V,Druddigon,dragon,1.6,139.0,77,120,90,60,90,48

# Top 10 Pokémon - Melhor Ataque

In [24]:
ranking_tipo.sort_values('attack',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,644,V,Zekrom,dragon,2.9,345.0,100,150,120,120,100,90
1,384,III,Rayquaza,dragon,7.0,206.5,105,150,90,150,90,95
2,612,V,Haxorus,dragon,1.8,105.5,76,147,90,60,70,97
3,373,III,Salamence,dragon,1.5,102.6,95,135,80,110,80,100
4,149,I,Dragonite,dragon,2.2,210.0,91,134,95,100,100,80
5,646,V,Kyurem,dragon,3.0,325.0,125,130,90,130,90,95
6,445,IV,Garchomp,dragon,1.9,95.0,108,130,95,80,85,102
7,643,V,Reshiram,dragon,3.2,330.0,100,120,100,150,120,90
8,621,V,Druddigon,dragon,1.6,139.0,77,120,90,60,90,48
9,611,V,Fraxure,dragon,1.0,36.0,66,117,70,40,50,67

# Top 10 Pokémon - Melhor Defesa

In [25]:
ranking_tipo.sort_values('defense',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,644,V,Zekrom,dragon,2.9,345.0,100,150,120,120,100,90
1,643,V,Reshiram,dragon,3.2,330.0,100,120,100,150,120,90
2,372,III,Shelgon,dragon,1.1,110.5,65,95,100,60,50,50
3,149,I,Dragonite,dragon,2.2,210.0,91,134,95,100,100,80
4,445,IV,Garchomp,dragon,1.9,95.0,108,130,95,80,85,102
5,621,V,Druddigon,dragon,1.6,139.0,77,120,90,60,90,48
6,612,V,Haxorus,dragon,1.8,105.5,76,147,90,60,70,97
7,646,V,Kyurem,dragon,3.0,325.0,125,130,90,130,90,95
8,380,III,Latias,dragon,1.4,40.0,80,80,90,110,130,110
9,334,III,Altaria,dragon,1.1,20.6,75,70,90,70,105,80

# Top 10 Pokémon - Melhor Ataque Especial

In [26]:
ranking_tipo.sort_values('sp_attack',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,384,III,Rayquaza,dragon,7.0,206.5,105,150,90,150,90,95
1,643,V,Reshiram,dragon,3.2,330.0,100,120,100,150,120,90
2,646,V,Kyurem,dragon,3.0,325.0,125,130,90,130,90,95
3,381,III,Latios,dragon,2.0,60.0,80,90,80,130,110,110
4,644,V,Zekrom,dragon,2.9,345.0,100,150,120,120,100,90
5,373,III,Salamence,dragon,1.5,102.6,95,135,80,110,80,100
6,380,III,Latias,dragon,1.4,40.0,80,80,90,110,130,110
7,149,I,Dragonite,dragon,2.2,210.0,91,134,95,100,100,80
8,445,IV,Garchomp,dragon,1.9,95.0,108,130,95,80,85,102
9,334,III,Altaria,dragon,1.1,20.6,75,70,90,70,105,80

# Top 10 Pokémon - Melhor Defesa Especial

In [27]:
ranking_tipo.sort_values('sp_defense',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,380,III,Latias,dragon,1.4,40.0,80,80,90,110,130,110
1,643,V,Reshiram,dragon,3.2,330.0,100,120,100,150,120,90
2,381,III,Latios,dragon,2.0,60.0,80,90,80,130,110,110
3,334,III,Altaria,dragon,1.1,20.6,75,70,90,70,105,80
4,149,I,Dragonite,dragon,2.2,210.0,91,134,95,100,100,80
5,644,V,Zekrom,dragon,2.9,345.0,100,150,120,120,100,90
6,646,V,Kyurem,dragon,3.0,325.0,125,130,90,130,90,95
7,384,III,Rayquaza,dragon,7.0,206.5,105,150,90,150,90,95
8,621,V,Druddigon,dragon,1.6,139.0,77,120,90,60,90,48
9,445,IV,Garchomp,dragon,1.9,95.0,108,130,95,80,85,102

# Top 10 Pokémon - Melhor Velocidade

In [28]:
ranking_tipo.sort_values('speed',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,380,III,Latias,dragon,1.4,40.0,80,80,90,110,130,110
1,381,III,Latios,dragon,2.0,60.0,80,90,80,130,110,110
2,445,IV,Garchomp,dragon,1.9,95.0,108,130,95,80,85,102
3,373,III,Salamence,dragon,1.5,102.6,95,135,80,110,80,100
4,612,V,Haxorus,dragon,1.8,105.5,76,147,90,60,70,97
5,646,V,Kyurem,dragon,3.0,325.0,125,130,90,130,90,95
6,384,III,Rayquaza,dragon,7.0,206.5,105,150,90,150,90,95
7,644,V,Zekrom,dragon,2.9,345.0,100,150,120,120,100,90
8,643,V,Reshiram,dragon,3.2,330.0,100,120,100,150,120,90
9,444,IV,Gabite,dragon,1.4,56.0,68,90,65,50,55,82