In [100]:
import pandas as pd

In [101]:
pokemon_df = pd.read_csv('pokemon.csv')

In [102]:
pokemon_df.drop(['is_sublegendary','is_legendary','is_mythical'],axis=1, inplace=True)
pokemon_df.rename(columns={'national_number':'Nº'},inplace=True)

In [103]:
pokemon_df.head(10)

,Nº,gen,Name,primary_type,secondary_type,percent_male,percent_female,height_m,weight_kg,capture_rate,...,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,gigantamax,mega_evolution,mega_evolution_alt
0,1,I,Bulbasaur,grass,poison,88.14,11.86,0.7,6.9,45,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,NaN,NaN,NaN
1,2,I,Ivysaur,grass,poison,88.14,11.86,1.0,13.0,45,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,NaN,NaN,NaN
2,3,I,Venusaur,grass,poison,88.14,11.86,2.0,100.0,45,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,Gigantamax Venusaur,Mega Venusaur,NaN
3,4,I,Charmander,fire,NaN,88.14,11.86,0.6,8.5,45,...,0.50,2.0,1.0,1.0,1.0,0.5,0.5,NaN,NaN,NaN
4,5,I,Charmeleon,fire,NaN,88.14,11.86,1.1,19.0,45,...,0.50,2.0,1.0,1.0,1.0,0.5,0.5,NaN,NaN,NaN
5,6,I,Charizard,fire,flying,88.14,11.86,1.7,90.5,45,...,0.25,4.0,1.0,1.0,1.0,0.5,0.5,Gigantamax Charizard,Mega Charizard X,Mega Charizard Y
6,7,I,Squirtle,water,NaN,88.14,11.86,0.5,9.0,45,...,1.00,1.0,1.0,1.0,1.0,0.5,1.0,NaN,NaN,NaN
7,8,I,Wartortle,water,NaN,88.14,11.86,1.0,22.5,45,...,1.00,1.0,1.0,1.0,1.0,0.5,1.0,NaN,NaN,NaN
8,9,I,Blastoise,water,NaN,88.14,11.86,1.6,85.5,45,...,1.00,1.0,1.0,1.0,1.0,0.5,1.0,Gigantamax Blastoise,Mega Blastoise,NaN
9,10,I,Caterpie,bug,NaN,50.2,49.8,0.3,2.9,255,...,1.00,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN

In [104]:
selecao_grama = (pokemon_df['primary_type'] == 'grass') & (pokemon_df['gen'] != 'VIII') & (pokemon_df['gen'] != 'VII') & (pokemon_df['gen'] != 'VI')


pokemon_grama = pokemon_df[selecao_grama]

In [105]:
ranking_grama = pokemon_grama[['Nº','gen','Name','primary_type','height_m','weight_kg','hp','attack','defense','sp_attack','sp_defense','speed']]

# Top 10 pokemon tipo grama - Melhor HP

In [106]:
ranking_grama.sort_values('hp',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,591,V,Amoonguss,grass,0.6,10.5,114,85,70,85,80,30
1,465,IV,Tangrowth,grass,2.0,128.6,100,100,125,110,50,50
2,492,IV,Shaymin,grass,0.2,2.1,100,100,100,100,100,100
3,357,III,Tropius,grass,2.0,100.0,99,68,83,72,87,51
4,389,IV,Torterra,grass,2.2,310.0,95,109,105,75,85,56
5,103,I,Exeggutor,grass,2.0,120.0,95,95,85,125,75,55
6,640,V,Virizion,grass,2.0,200.0,91,90,72,90,129,108
7,275,III,Shiftry,grass,1.3,59.6,90,100,60,90,60,80
8,460,IV,Abomasnow,grass,2.2,135.5,90,92,75,92,85,60
9,3,I,Venusaur,grass,2.0,100.0,80,82,83,100,100,80

# Top 10 pokemon tipo grama - Melhor Ataque

In [107]:
ranking_grama.sort_values('attack',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,286,III,Breloom,grass,1.2,39.2,60,130,80,60,60,70
1,332,III,Cacturne,grass,1.3,77.4,70,115,60,115,60,55
2,470,IV,Leafeon,grass,1.0,25.5,65,110,130,60,65,95
3,389,IV,Torterra,grass,2.2,310.0,95,109,105,75,85,56
4,71,I,Victreebel,grass,1.7,15.5,80,105,65,100,70,70
5,455,IV,Carnivine,grass,1.4,27.0,74,100,72,90,72,46
6,465,IV,Tangrowth,grass,2.0,128.6,100,100,125,110,50,50
7,275,III,Shiftry,grass,1.3,59.6,90,100,60,90,60,80
8,492,IV,Shaymin,grass,0.2,2.1,100,100,100,100,100,100
9,512,V,Simisage,grass,1.1,30.5,75,98,63,98,63,101

# Top 10 pokemon tipo grama - Melhor Defesa

In [108]:
ranking_grama.sort_values('defense',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,598,V,Ferrothorn,grass,1.0,110.0,74,94,131,54,116,20
1,470,IV,Leafeon,grass,1.0,25.5,65,110,130,60,65,95
2,465,IV,Tangrowth,grass,2.0,128.6,100,100,125,110,50,50
3,114,I,Tangela,grass,1.0,35.0,65,55,115,100,40,60
4,389,IV,Torterra,grass,2.2,310.0,95,109,105,75,85,56
5,492,IV,Shaymin,grass,0.2,2.1,100,100,100,100,100,100
6,154,II,Meganium,grass,1.8,100.5,80,82,100,83,100,80
7,497,V,Serperior,grass,3.3,63.0,75,75,95,75,95,113
8,182,II,Bellossom,grass,0.4,5.8,75,80,95,90,100,50
9,597,V,Ferroseed,grass,0.6,18.8,44,50,91,24,86,10

# Top 10 pokemon tipo grama - Melhor Ataque Especial

In [109]:
ranking_grama.sort_values('sp_attack',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,407,IV,Roserade,grass,0.9,14.5,60,70,65,125,105,90
1,103,I,Exeggutor,grass,2.0,120.0,95,95,85,125,75,55
2,332,III,Cacturne,grass,1.3,77.4,70,115,60,115,60,55
3,45,I,Vileplume,grass,1.2,18.6,75,80,85,110,90,50
4,549,V,Lilligant,grass,1.1,16.3,70,60,75,110,75,90
5,465,IV,Tangrowth,grass,2.0,128.6,100,100,125,110,50,50
6,556,V,Maractus,grass,1.0,28.0,75,86,67,106,67,60
7,192,II,Sunflora,grass,0.8,8.5,75,75,55,105,85,30
8,254,III,Sceptile,grass,1.7,52.2,70,85,65,105,85,120
9,114,I,Tangela,grass,1.0,35.0,65,55,115,100,40,60

# Top 10 pokemon tipo grama - Melhor Defesa Especial

In [110]:
ranking_grama.sort_values('sp_defense',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,640,V,Virizion,grass,2.0,200.0,91,90,72,90,129,108
1,598,V,Ferrothorn,grass,1.0,110.0,74,94,131,54,116,20
2,407,IV,Roserade,grass,0.9,14.5,60,70,65,125,105,90
3,154,II,Meganium,grass,1.8,100.5,80,82,100,83,100,80
4,3,I,Venusaur,grass,2.0,100.0,80,82,83,100,100,80
5,492,IV,Shaymin,grass,0.2,2.1,100,100,100,100,100,100
6,182,II,Bellossom,grass,0.4,5.8,75,80,95,90,100,50
7,189,II,Jumpluff,grass,0.8,3.0,75,55,70,55,95,110
8,497,V,Serperior,grass,3.3,63.0,75,75,95,75,95,113
9,45,I,Vileplume,grass,1.2,18.6,75,80,85,110,90,50

# Top 10 pokemon tipo grama - Melhor Velocidade

In [111]:
ranking_grama.sort_values('speed',ascending=False,ignore_index=True).head(10)

,Nº,gen,Name,primary_type,height_m,weight_kg,hp,attack,defense,sp_attack,sp_defense,speed
0,254,III,Sceptile,grass,1.7,52.2,70,85,65,105,85,120
1,547,V,Whimsicott,grass,0.7,6.6,60,67,85,77,75,116
2,497,V,Serperior,grass,3.3,63.0,75,75,95,75,95,113
3,189,II,Jumpluff,grass,0.8,3.0,75,55,70,55,95,110
4,640,V,Virizion,grass,2.0,200.0,91,90,72,90,129,108
5,512,V,Simisage,grass,1.1,30.5,75,98,63,98,63,101
6,492,IV,Shaymin,grass,0.2,2.1,100,100,100,100,100,100
7,470,IV,Leafeon,grass,1.0,25.5,65,110,130,60,65,95
8,253,III,Grovyle,grass,0.9,21.6,50,65,45,85,65,95
9,407,IV,Roserade,grass,0.9,14.5,60,70,65,125,105,90